"""Variation rule preset schema and defaults."""

from variation_engine.variation.presets import (
    DEFAULT_VARIATION_RULE_PRESET_ID,
    MAJOR_THIRDS_AROUND_SOURCE,
    SOURCE_ONLY,
    VARIATION_RULE_PRESET_BY_ID,
    VARIATION_RULE_PRESET_BY_PROFILE,
    VARIATION_RULE_PRESETS,
    NumericRange,
    PitchMappingPreset,
    VariationRulePreset,
    VariationTransformRanges,
    get_variation_rule_preset,
    get_variation_rule_preset_for_profile,
)
from variation_engine.variation.planner import (
    AnalysisPitchSummary,
    AnalysisProfileSummary,
    FilePlanSummary,
    InvalidNoteNameError,
    SelectedCategorySummary,
    SelectedPresetSummary,
    SourceNote,
    TargetNote,
    VariationPlan,
    VariationPlanResult,
    VariationPlanStatus,
    build_target_notes,
    create_variation_plan,
    midi_note_to_name,
    parse_note_name,
)

__all__ = [
    "DEFAULT_VARIATION_RULE_PRESET_ID",
    "MAJOR_THIRDS_AROUND_SOURCE",
    "SOURCE_ONLY",
    "VARIATION_RULE_PRESET_BY_ID",
    "VARIATION_RULE_PRESET_BY_PROFILE",
    "VARIATION_RULE_PRESETS",
    "NumericRange",
    "PitchMappingPreset",
    "VariationRulePreset",
    "VariationTransformRanges",
    "get_variation_rule_preset",
    "get_variation_rule_preset_for_profile",
    "AnalysisPitchSummary",
    "AnalysisProfileSummary",
    "FilePlanSummary",
    "InvalidNoteNameError",
    "SelectedCategorySummary",
    "SelectedPresetSummary",
    "SourceNote",
    "TargetNote",
    "VariationPlan",
    "VariationPlanResult",
    "VariationPlanStatus",
    "build_target_notes",
    "create_variation_plan",
    "midi_note_to_name",
    "parse_note_name",
]
